
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY NotifyMe/NotifyMe.csproj NotifyMe/NotifyMe/
COPY NotifyMe.Common/NotifyMe.Common.csproj NotifyMe/

RUN dotnet restore NotifyMe/NotifyMe/NotifyMe.csproj
WORKDIR /src/NotifyMe/NotifyMe
COPY . .
RUN dotnet build NotifyMe/NotifyMe.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish NotifyMe/NotifyMe.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "NotifyMe.dll"]
